name: flutter_design_guard
description: A modern Dart analysis server plugin for enforcing Flutter design-system rules in Flutter projects.
version: 0.1.0

repository: https://github.com/hosaaam/flutter_design_guard
issue_tracker: https://github.com/hosaaam/flutter_design_guard/issues

environment:
  sdk: ">=3.11.0 <4.0.0"

topics:
  - analyzer
  - flutter
  - lints
  - static-analysis
  - code-quality

dependencies:
  analysis_server_plugin: ^0.3.20
  analyzer: ^14.1.0
  analyzer_plugin: ^0.14.14
  yaml: ^3.1.3

dev_dependencies:
  analyzer_testing: ^0.3.4
  lints: ^6.1.0
  test: ^1.31.2
  test_reflective_loader: ^0.4.0
